server:
  port: 7005

spring:
  application:
    name: payment-service
  data:
    mongodb:
      database: CaseStudy-OnlineShoppingCart
      host: localhost
      port: 27017

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    hostname: localhost
